name: Lint

on:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  pre-commit:
    name: "Pre-commit"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
