name: Lint

on:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  pre-commit:
    name: "Pre-commit"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7.6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
